ARCH=$(uname -m)
ARTIFACT="WasmEdge-plugin-wasi_nn-ggml-${WASMEDGE_GGML_BUILD}-${WASMEDGE_VERSION}-ubuntu20.04-${ARCH}.tar.gz"
IS_NATIVE=OFF

if [[ "${ARCH}" == "x86_64" ]; then
  IS_NATIVE=ON
fi

cmake -B${OUTPUT_DIR} -GNinja \
  -DCMAKE_BUILD_TYPE=Release \
  -DWASMEDGE_BUILD_AOT_RUNTIME=OFF \
  -DWASMEDGE_BUILD_TOOLS=OFF \
  -DWASMEDGE_PLUGIN_WASI_NN_BACKEND=GGML \
  -DWASMEDGE_PLUGIN_WASI_NN_GGML_LLAMA_BLAS=OFF \
  -DWASMEDGE_PLUGIN_WASI_NN_GGML_LLAMA_NATIVE=${IS_NATIVE} \
  -DWASMEDGE_USE_LLVM=OFF
cmake --build ${OUTPUT_DIR}

cp -f "${OUTPUT_DIR}/${OUTPUT_BIN}" "${OUTPUT_BIN}"
tar zcvf "${ARTIFACT}" "${OUTPUT_BIN}"

echo "artifact=${ARTIFACT}" >> "${GITHUB_OUTPUT}"
